eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost

hystrix:
  command:
    fallabackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
